### ISSUE TITLE
Option to center lyrics 

### ISSUE THREAD

**Issue by jeremiahlukus** [paurakhsharma/flutter_chord#17]
While this looks fine normally on landscape mode it would be nice to pass in a param like centerText. Are you ok if i send a PR for this?

**Comment by jeremiahlukus** [comment]
<img width="939" alt="Screen Shot 2023-02-15 at 9 22 02 PM" src="https://user-images.githubusercontent.com/17206638/219251494-f2204603-e0f0-4658-85b6-97bcd0180a76.png">

Here is what is looks like in landscape. 

The PR would be making this line 
https://github.com/paurakhsharma/flutter_chord/blob/main/lib/src/lyrics_renderer.dart#L141 an optional param 

```
centerLyricText ? CrossAxisAlignment.center : CrossAxisAlignment.start
```

**Comment by paurakhsharma** [comment]
@jeremiahlukus It is a good feature request. But I am not sure just using `enterLyricText ? CrossAxisAlignment.center : CrossAxisAlignment.start` will fix it as the row for lyrics and chords can have different width. 

But let's try and see if it works.

One suggestion, let's use `lyricsAlign` which takes type of `CrossAxisAlignment` so that user can have a flexibility of aligning it as they want.

**Comment by jeremiahlukus** [comment]
Ok the chord.leadingSpace 
https://github.com/paurakhsharma/flutter_chord/blob/main/lib/src/chord_parser.dart#L145. 

Makes this much more interesting. A little more more work than i assumed im going to close this issue.

**Comment by jeremiahlukus** [comment]
Opening this back up and will start looking into this now that my app is live @paurakhsharma
